[package]
name = "blitzortung"
version = "0.1.3"
edition = "2021"
description = "Unofficial Blitzortung.org client"
license = "MIT"
repository = "https://github.com/akeamc/blitzortung"

[[bench]]
name = "ws_msg_decode"
harness = false
required-features = ["live"]

[dependencies]
futures = "0.3.21"
geo = { version = "0.20.1", optional = true }
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
time = { version = "0.3.9", optional = true, features = ["serde-well-known"] }
tokio = { version = "1.18.2", features = ["net"] }
tokio-tungstenite = { version = "0.17.1", features = ["native-tls"], optional = true }
tracing = { version = "0.1.37", optional = true }

[features]
live = ["dep:tokio-tungstenite", "dep:rand", "dep:time"]

[dev-dependencies]
criterion = "0.3.5"
tokio-test = "0.4.2"

[package.metadata.docs.rs]
all-features = true
