[package]
name = "lightningalert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
blitzortung = "0.1"
futures = "0.3.21"
tokio = { version = "1.18.2", features = ["rt", "rt-multi-thread", "macros"] }
